JavaScript/Semana1/e-commerce2022/client/js/index.js, JavaScript/Semana1/e-commerce2022/client/js/products.js
se carga el ejercicio cierra issues #13
=>  Avanzamos con css y js (video3)

Java/semana01/EstudianteDAO.java
estoy probando porque no me estaba saliendo de esta forma, avisame si sale bien! gracias #15 #16
=> 1.1 Método eliminar estudiante y prueba

Python/Semana1/usuario.py
=> Creacion de usuario

Node/Semana2/app.js
Acá está lo de la semana 2 en node
=> Node semana 2

Java/Semana3/EstudianteRepositorio.java, Python/Semana3/tipo_float.py
Tipo float como constructor y comienzo de exponencial #37
=> Clase 02 Python - 2.3 video 4

Java/Semana3/Estudiante.java, Python/Semana3/valores_infinitos.py
Esta carga de ejercicio cierra el issue #46
=> Creación del paquete modelo ...(video3)

Java/semana04/EstudianteServicio.java, JavaScript/Semana4/cart.js, Python/semana4/tipo_bool.py
=> Tareas de la semana 4

JavaScript/Semana2/e-commerce2022/client/js/cart.js
Avanzamos con el body, el video es de el 1 de la clase 3 de js. #55
=> 3.1 Avanzamos en el Body(VIDEO 1)#55

Python/Semana02/Clase01/tipo_float.py
=> Video 4 semana 2 de python y videos 5 y 6 semana 3 de java

Java/semana02/ProyectosJava/Leccion01/estudiantes/src/main/java/utn/estudiantes/EstudiantesApplication.java
Se agregaron las lineas correspondientes al video 7 de la clase 4  semana 4 #79
=> EstudianteAplicacion

JavaScript/Semana4/cart.js
3.6 Eliminar productos del modal --
parte 2(video 7)
=> 3.6 Eliminar productos del modal -- parte 2(video 7)

Java/ProyectoJava+SpringBoot/Leccion01/estudiantes/src/main/java/utn/estudiantes/modelo/Estudiantes2022.java, Java/ProyectoJava+SpringBoot/Leccion01/estudiantes/src/main/java/utn/estudiantes/servicio/EEstudianteServicio.java
5.1 Orientación hacía la buena configuración (video 1) 
5.2 Aplicación en las teorías (video 2)
#96 #97
=> Clase 05 Java - Issues #96 #97

Node/semana5/monohilo.js
=> video 3 y 4 Node

Python/Semana07/f_string.py
6.5 Uso del método print() para dar formato en la salida(VIDEO 7) #130
=> --- CLASE 06 PYTHON --- 6.5

.gitignore, JavaScript/Leccion02/proyecto-PERN-stack/package.json, JavaScript/Leccion02/proyecto-PERN-stack/src/index.js
#118 Instalación de dependencias para desarrollo (video 4).
#119 Creación de las carpetas para el backend (video 5).
=> Clase 05 JavaScript - #118 #119 (video 4 y 5)

JavaScript/Leccion02/proyecto-PERN-stack/.gitignore, JavaScript/Leccion02/proyecto-PERN-stack/src/app.js, JavaScript/Leccion02/proyecto-PERN-stack/src/index.js
Esta carga de ejercicio cierre issue #120 #121
=> Creación de carpeta database y del servidor express(video 6 y 7)

Python/Semana07/dar_formato_str.py
Video 5, uso del método format()
=> Clase 06 Python - 6.3 #128

JavaScript/Leccion02/proyecto-PERN-stack/package.json, JavaScript/Leccion02/proyecto-PERN-stack/src/controllers/auth.controller.js
Se realizo modificaciones  modificaciones en auth.controller.js y se instaló bcrypt #158 #159
=> CLASE 07 JAVASCRIPT videos 3 y 4

JavaScript/Leccion02/proyecto-PERN-stack/database/init.sql, JavaScript/Leccion02/proyecto-PERN-stack/src/router/auth.routes.js
actualización de init.sql y auth.routers
=> Clase 07 JS video 1 y 2

Java/ProyectoJava+SpringBoot/Leccion03/tienda_libros/src/main/java/utn/tienda_libros/vista/LibroFrom.java
-Terminando con el botón modificar
-Eliminar libro -> Botón eliminar
=> Clase 10 Java - #202 #203 (video 5 y 6)
